-- script for initializing view for data extraction.
-- author		: nattapong laiyapark
-- creation date	: Aug 30 2016
-----------------------------------------------------------------------------------------------------------------------------------
-- developer notes	: 
--			  
--			  
-----------------------------------------------------------------------------------------------------------------------------------
-- revision history ----------------------------------------------------------------------------------------------------------
-- 2016-08-30	nattapong laiyapark	creation of this initialization script.
-- 2016-08-30	chonlathep phosaithong	add STG_TNB_TRN_CONTRACT_MONTHEND AND STG_TNB_MST_BOT_CLASS VIEW
-- 2016-11-22	suppakorn choochom	add STG_TNB_TRN_APP_IN_LOG View
----------------------------------------------------------------------------------------------------------------------------------
------------------------------------- c a u t i o n ------------------------------------------------------------------------------
-- do not run this script in a production environment.
-- existing data will be lost. make sure database backup exists before running this script 
-----------------------------------------------------------------------------------------------------------------------------------

/** DROP all views **/
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_TRN_CONTRACT_MONTHEND')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_TRN_CONTRACT_MONTHEND
	END
GO
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_TRN_CONTRACT_MONTHEND_DELTA')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_TRN_CONTRACT_MONTHEND_DELTA
	END
GO
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_TRN_CONTRACT')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_TRN_CONTRACT
	END
GO
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_TRN_APPLICATION')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_TRN_APPLICATION 
	END
GO
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_TRN_APP_IN_LOG')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_TRN_APP_IN_LOG
	END
GO
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_MST_ACCOUNT_STATUS')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_MST_ACCOUNT_STATUS
	END
GO
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_MST_REQUEST_STATUS')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_MST_REQUEST_STATUS
	END
GO
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_MST_PRODUCT')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_MST_PRODUCT
	END
GO
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_MST_CUST_SOURCE')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_MST_CUST_SOURCE 
	END
GO
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_MST_BRANCH')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_MST_BRANCH 
	END
GO
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_MST_DEALER')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_MST_DEALER 
	END
GO
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_MST_BOT_CLASS')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_MST_BOT_CLASS
	END
GO
------------------------------------------------------------------------------------------------------------------

/** Schema Creation **/
IF EXISTS (SELECT NAME FROM SYS.SCHEMAS WHERE NAME = N'BI')
	BEGIN
		DROP SCHEMA BI
	END
GO
CREATE SCHEMA BI
GO
--------------------------------------------------------------------------------------------------------------------

/** Create Transaction view **/

 --STG_TNB_TRN_CONTRACT_MONTHEND
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_TRN_CONTRACT_MONTHEND')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_TRN_CONTRACT_MONTHEND
	END
GO
CREATE VIEW BI.V_TADS_STG_TNB_TRN_CONTRACT_MONTHEND --STG_TNB_TRN_CONTRACT_MONTHEND
AS SELECT MSOL_REC_STS
      ,MSOL_LN_BRN
      ,MSOL_LN_TYP
      ,MSOL_DOC_NO
      ,MSOL_CHECK_DIGIT
      ,MSOL_YEAR
      ,MSOL_MONTH
      ,MSOL_UID_PERIOD
      ,MSOL_OS_BAL
      ,MSOL_OS_BAL_VAT
      ,MSOL_CHQ_EFF
      ,MSOL_PAY_PRINCIPAL
      ,MSOL_PAY_VAT_AMT
      ,MSOL_OS_UID_PRINCIPAL
      ,MSOL_OS_UID_AMOUNT
      ,MSOL_REALIZED_UID_AMT
      ,MSOL_REVERSE_UID_AMT
      ,MSOL_REALIZED_PAID
      ,MSOL_REALIZED_UNPAID
      ,MSOL_OS_SUBSIDY_AMT
      ,MSOL_REALIZED_SUBSIDY
      ,MSOL_REVERSE_SUBSIDY
      ,MSOL_OS_EXPENSE_AMT
      ,MSOL_REALIZED_EXPENSE
      ,MSOL_REVERSE_EXPENSE
      ,MSOL_OS_INS_FREE_AMT
      ,MSOL_REALIZED_INS_FREE
      ,MSOL_REVERSE_INS_FREE
      ,MSOL_ACC_INT
      ,MSOL_STOP_DATE
      ,MSOL_NEXT_PAY_PRINCIPAL_DATE
      ,MSOL_LST_PAY_PERIOD_PRINCIPAL
      ,MSOL_MATURITY_DATE
      ,MSOL_TERM
      ,MSOL_VALUE_DATE
      ,MSOL_AGING_TERM
      ,MSOL_AGING_DAY
      ,MSOL_GRADE
      ,MSOL_STATUS_FLAG
      ,MSOL_AST_STS
      ,MSOL_STOP_VAT_FLAG
      ,MSOL_RELIEVE_FLAG
      ,MSOL_DUE_PERIOD
      ,MSOL_BEFORE_REL_UID_SEQ
      ,MSOL_AFTER_REL_UID_SEQ
      ,MSOL_OS_HEALTH_INS_AMT
      ,MSOL_REALIZED_HEALTH_INS
      ,MSOL_OS_LIFE_INS_AMT
      ,MSOL_REALIZED_LIFE_INS
      ,MSOL_ACCRUED_EOM
      ,MSOL_PROVISION_AMT
      ,MSOL_OS_UID1_AMOUNT
      ,MSOL_CHANGE_STATUS_DATE
      ,MSOL_REPO_DATE
      ,MSOL_REPO_SELL_DATE
      ,MSOL_PRINT_CANCEL_LETTER_DATE
      ,MSOL_REPO_FLAG
      ,MSOL_OS_AR_VAT
      ,MSOL_SEQ_UID_RD
      ,MSOL_REALIZED_RD_THIS_MTH
      ,MSOL_PAY_PRINCIPAL_THIS_YEAR
      ,MSOL_PAY_PRINCIPAL_ALL
      ,MSOL_INSTALL_PASS_DUE
      ,MSOL_OVER_1_YEAR
      ,MSOL_FLAG
      ,MSOL_BAL_INSTALL_NEXT_PRINC
      ,MSOL_VAT_PASS_DUE
      ,MSOL_AST_STS_ACTUAL
      ,MSOL_LAST_PAY_DATE
      ,MSOL_CLOSE_AMORTIZE_DATE
      ,MSOL_CLOSE_AMORTIZE_FLAG
      ,MSOL_PREV_YEAR
      ,MSOL_PREV_MONTH
      ,MSOL_WO_DATE
      ,MSOL_PAY_VAT_ALL
      ,MSOL_DISCOUNT_AMOUNT
      ,MSOL_PREV_GRADE
      ,MSOL_PREV_STATUS_FLAG
      ,MSOL_PREV_AST_STS_ACTUAL
      ,MSOL_PAY_PRINCIPAL_ADJ
      ,MSOL_PAY_VAT_AMT_ADJ
      ,MSOL_PAY_PRINCIPAL_WO
      ,MSOL_PAY_VAT_AMT_WO
      ,MSOL_FORECLOSE_PROP_FLAG
      ,MSOL_DAMAGE_AMT_INC_VAT
      ,MSOL_COLLECTOR_CODE
      ,MSOL_INSTALL_PERIOD_NEXT_MTH
      ,MSOL_INSTALL_OVER_DUE_NEXT_MTH
      ,MSOL_COST_ESTIMATE
      ,MSOL_ESTIMATE_DATE
      ,MSOL_PAY_PRINCIPAL_ADJ_THIS_YY
      ,MSOL_PAY_PRINCIPAL_WO_THIS_YY
      ,MSOL_REALIZE_UNEARN
      ,MSOL_EOM_UNEARN
      ,MSOL_CF_UNEARN
      ,MSOL_REALIZE_UNEARN_SURPLUS
      ,MSOL_EOM_UNEARN_SURPLUS
      ,MSOL_CF_UNEARN_SURPLUS
      ,MSOL_REALIZE_OTHER_SURPLUS
      ,MSOL_EOM_OTHER_SURPLUS
      ,MSOL_CF_OTHER_SURPLUS
      ,MSOL_REALIZE_PAID_UNEARN
      ,MSOL_REALIZE_PAID_UNEARN_YEAR
      ,MSOL_REALIZE_PAID_UNEARN_MONTH
      ,MSOL_REALIZE_UNPAID_UNEARN
      ,MSOL_OS_UID1_UNEARN
      ,MSOL_REVERSE_UNEARN
      ,MSOL_REALIZE_PAID_SURPLUS
      ,MSOL_REALIZE_PAID_SURPLUS_YEAR
      ,MSOL_REALIZE_PAID_SURPLUS_MONTH
      ,MSOL_REALIZE_UNPAID_SURPLUS
      ,MSOL_EOM_SURPLUS
      ,MSOL_OS_UID1_SURPLUS
      ,MSOL_REVERSE_SURPLUS
      ,MSOL_REALIZE_PAID_OTHER
      ,MSOL_REALIZE_PAID_OTHER_YEAR
      ,MSOL_REALIZE_PAID_OTHER_MONTH
      ,MSOL_REALIZE_UNPAID_OTHER
      ,MSOL_EOM_OTHER
      ,MSOL_OS_UID1_OTHER
      ,MSOL_REVERSE_OTHER
	  ,MSOL_OS_IN_YEAR
      ,MSOL_OS_MORE_YEAR
      ,MSOL_UNEARN_IN_YEAR
      ,MSOL_UNEARN_OTHER
      ,MSOL_UNEARN_OTHER_IN_YEAR
      ,MSOL_UNEARN_MORE_YEAR
      ,MSOL_UNEARN_OTHER_MORE_YEAR
      ,MSOL_PRINCIPAL_IN_YEAR
      ,MSOL_PRINCIPAL_MORE_YEAR
      ,MSOL_PROVISION_IN_YEAR
      ,MSOL_PROVISION_MORE_YEAR
      ,MSOL_NEW_PRINCIPAL
      ,MSOL_REALIZED_OTHER
      ,MSOL_REALIZED_OTHER_MONTH
      ,MSOL_REALIZED_OTHER_THIS_YEAR
      ,MSOL_NEW_PROVISION_AMT
      ,MSOL_REALIZED_EXP_INS_THIS_YEAR
      ,MSOL_REALIZED_EXP_INS
	  ,NULL AS JOB_RUN_KEY
	  ,'TELS' AS SOURCE_SYSTEM_CODE
	  ,'FNMSOL' AS SOURCE_TABLE_NAME
	  ,'N' DELETED_FLAG
	  ,GETDATE()-1 AS SOURCE_LAST_UPDATE_DATE_TIME --Remark. Need to get MLMH_MTN_DATE_TIME from FNMLMH to get last update time.
	  ,NULL AS LAST_UPDATE_DATE_TIME
  FROM FNMSOL SOL WITH(NOLOCK)
GO
PRINT SUBSTRING(CONVERT(NVARCHAR(33),CURRENT_TIMESTAMP,121),1,19) + ': V_TADS_STG_TNB_TRN_CONTRACT_MONTHEND VIEW CREATED.'
--------------------------------------------------------------------------------------------------------------------------

 --STG_TNB_TRN_CONTRACT_MONTHEND_DELTA
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_TRN_CONTRACT_MONTHEND_DELTA')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_TRN_CONTRACT_MONTHEND_DELTA
	END
GO
CREATE VIEW BI.V_TADS_STG_TNB_TRN_CONTRACT_MONTHEND_DELTA --STG_TNB_TRN_CONTRACT_MONTHEND
AS SELECT MSOL_REC_STS
      ,MSOL_LN_BRN
      ,MSOL_LN_TYP
      ,MSOL_DOC_NO
      ,MSOL_CHECK_DIGIT
      ,MSOL_YEAR
      ,MSOL_MONTH
      ,MSOL_UID_PERIOD
      ,MSOL_OS_BAL
      ,MSOL_OS_BAL_VAT
      ,MSOL_CHQ_EFF
      ,MSOL_PAY_PRINCIPAL
      ,MSOL_PAY_VAT_AMT
      ,MSOL_OS_UID_PRINCIPAL
      ,MSOL_OS_UID_AMOUNT
      ,MSOL_REALIZED_UID_AMT
      ,MSOL_REVERSE_UID_AMT
      ,MSOL_REALIZED_PAID
      ,MSOL_REALIZED_UNPAID
      ,MSOL_OS_SUBSIDY_AMT
      ,MSOL_REALIZED_SUBSIDY
      ,MSOL_REVERSE_SUBSIDY
      ,MSOL_OS_EXPENSE_AMT
      ,MSOL_REALIZED_EXPENSE
      ,MSOL_REVERSE_EXPENSE
      ,MSOL_OS_INS_FREE_AMT
      ,MSOL_REALIZED_INS_FREE
      ,MSOL_REVERSE_INS_FREE
      ,MSOL_ACC_INT
      ,MSOL_STOP_DATE
      ,MSOL_NEXT_PAY_PRINCIPAL_DATE
      ,MSOL_LST_PAY_PERIOD_PRINCIPAL
      ,MSOL_MATURITY_DATE
      ,MSOL_TERM
      ,MSOL_VALUE_DATE
      ,MSOL_AGING_TERM
      ,MSOL_AGING_DAY
      ,MSOL_GRADE
      ,MSOL_STATUS_FLAG
      ,MSOL_AST_STS
      ,MSOL_STOP_VAT_FLAG
      ,MSOL_RELIEVE_FLAG
      ,MSOL_DUE_PERIOD
      ,MSOL_BEFORE_REL_UID_SEQ
      ,MSOL_AFTER_REL_UID_SEQ
      ,MSOL_OS_HEALTH_INS_AMT
      ,MSOL_REALIZED_HEALTH_INS
      ,MSOL_OS_LIFE_INS_AMT
      ,MSOL_REALIZED_LIFE_INS
      ,MSOL_ACCRUED_EOM
      ,MSOL_PROVISION_AMT
      ,MSOL_OS_UID1_AMOUNT
      ,MSOL_CHANGE_STATUS_DATE
      ,MSOL_REPO_DATE
      ,MSOL_REPO_SELL_DATE
      ,MSOL_PRINT_CANCEL_LETTER_DATE
      ,MSOL_REPO_FLAG
      ,MSOL_OS_AR_VAT
      ,MSOL_SEQ_UID_RD
      ,MSOL_REALIZED_RD_THIS_MTH
      ,MSOL_PAY_PRINCIPAL_THIS_YEAR
      ,MSOL_PAY_PRINCIPAL_ALL
      ,MSOL_INSTALL_PASS_DUE
      ,MSOL_OVER_1_YEAR
      ,MSOL_FLAG
      ,MSOL_BAL_INSTALL_NEXT_PRINC
      ,MSOL_VAT_PASS_DUE
      ,MSOL_AST_STS_ACTUAL
      ,MSOL_LAST_PAY_DATE
      ,MSOL_CLOSE_AMORTIZE_DATE
      ,MSOL_CLOSE_AMORTIZE_FLAG
      ,MSOL_PREV_YEAR
      ,MSOL_PREV_MONTH
      ,MSOL_WO_DATE
      ,MSOL_PAY_VAT_ALL
      ,MSOL_DISCOUNT_AMOUNT
      ,MSOL_PREV_GRADE
      ,MSOL_PREV_STATUS_FLAG
      ,MSOL_PREV_AST_STS_ACTUAL
      ,MSOL_PAY_PRINCIPAL_ADJ
      ,MSOL_PAY_VAT_AMT_ADJ
      ,MSOL_PAY_PRINCIPAL_WO
      ,MSOL_PAY_VAT_AMT_WO
      ,MSOL_FORECLOSE_PROP_FLAG
      ,MSOL_DAMAGE_AMT_INC_VAT
      ,MSOL_COLLECTOR_CODE
      ,MSOL_INSTALL_PERIOD_NEXT_MTH
      ,MSOL_INSTALL_OVER_DUE_NEXT_MTH
      ,MSOL_COST_ESTIMATE
      ,MSOL_ESTIMATE_DATE
      ,MSOL_PAY_PRINCIPAL_ADJ_THIS_YY
      ,MSOL_PAY_PRINCIPAL_WO_THIS_YY
      ,MSOL_REALIZE_UNEARN
      ,MSOL_EOM_UNEARN
      ,MSOL_CF_UNEARN
      ,MSOL_REALIZE_UNEARN_SURPLUS
      ,MSOL_EOM_UNEARN_SURPLUS
      ,MSOL_CF_UNEARN_SURPLUS
      ,MSOL_REALIZE_OTHER_SURPLUS
      ,MSOL_EOM_OTHER_SURPLUS
      ,MSOL_CF_OTHER_SURPLUS
      ,MSOL_REALIZE_PAID_UNEARN
      ,MSOL_REALIZE_PAID_UNEARN_YEAR
      ,MSOL_REALIZE_PAID_UNEARN_MONTH
      ,MSOL_REALIZE_UNPAID_UNEARN
      ,MSOL_OS_UID1_UNEARN
      ,MSOL_REVERSE_UNEARN
      ,MSOL_REALIZE_PAID_SURPLUS
      ,MSOL_REALIZE_PAID_SURPLUS_YEAR
      ,MSOL_REALIZE_PAID_SURPLUS_MONTH
      ,MSOL_REALIZE_UNPAID_SURPLUS
      ,MSOL_EOM_SURPLUS
      ,MSOL_OS_UID1_SURPLUS
      ,MSOL_REVERSE_SURPLUS
      ,MSOL_REALIZE_PAID_OTHER
      ,MSOL_REALIZE_PAID_OTHER_YEAR
      ,MSOL_REALIZE_PAID_OTHER_MONTH
      ,MSOL_REALIZE_UNPAID_OTHER
      ,MSOL_EOM_OTHER
      ,MSOL_OS_UID1_OTHER
      ,MSOL_REVERSE_OTHER
	  ,MSOL_OS_IN_YEAR
      ,MSOL_OS_MORE_YEAR
      ,MSOL_UNEARN_IN_YEAR
      ,MSOL_UNEARN_OTHER
      ,MSOL_UNEARN_OTHER_IN_YEAR
      ,MSOL_UNEARN_MORE_YEAR
      ,MSOL_UNEARN_OTHER_MORE_YEAR
      ,MSOL_PRINCIPAL_IN_YEAR
      ,MSOL_PRINCIPAL_MORE_YEAR
      ,MSOL_PROVISION_IN_YEAR
      ,MSOL_PROVISION_MORE_YEAR
      ,MSOL_NEW_PRINCIPAL
      ,MSOL_REALIZED_OTHER
      ,MSOL_REALIZED_OTHER_MONTH
      ,MSOL_REALIZED_OTHER_THIS_YEAR
      ,MSOL_NEW_PROVISION_AMT
      ,MSOL_REALIZED_EXP_INS_THIS_YEAR
      ,MSOL_REALIZED_EXP_INS
	  ,NULL AS JOB_RUN_KEY
	  ,'TELS' AS SOURCE_SYSTEM_CODE
	  ,'FNMSOL' AS SOURCE_TABLE_NAME
	  ,'N' DELETED_FLAG
	  ,GETDATE()-1 AS SOURCE_LAST_UPDATE_DATE_TIME --Remark. Need to get MLMH_MTN_DATE_TIME from FNMLMH to get last update time.
	  ,NULL AS LAST_UPDATE_DATE_TIME
  FROM FNMSOL SOL WITH(NOLOCK)
  WHERE ((MSOL_YEAR = YEAR(DATEADD(s,-1,DATEADD(mm, DATEDIFF(m,0,GETDATE()),0)))) AND (MSOL_MONTH = MONTH(DATEADD(s,-1,DATEADD(mm, DATEDIFF(m,0,GETDATE()),0))))) OR
  ((MSOL_YEAR = YEAR(DATEADD(s,-1,DATEADD(mm, DATEDIFF(m,0,GETDATE())+1,0)))) AND (MSOL_MONTH = MONTH(DATEADD(s,-1,DATEADD(mm, DATEDIFF(m,0,GETDATE())+1,0)))))
GO
PRINT SUBSTRING(CONVERT(NVARCHAR(33),CURRENT_TIMESTAMP,121),1,19) + ': V_TADS_STG_TNB_TRN_CONTRACT_MONTHEND_DELTA VIEW CREATED.'
--------------------------------------------------------------------------------------------------------------------------

--STG_TNB_TRN_CONTRACT 
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_TRN_CONTRACT')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_TRN_CONTRACT
	END
GO
CREATE VIEW BI.V_TADS_STG_TNB_TRN_CONTRACT
AS SELECT
			MLHP_REC_STS
			,MLHP_BRN_DOC
			,MLHP_REQ_DOC
			,MLHP_DOC_NO
			,MLHP_CHECK_DIGIT
			,MLHP_SELLING_PLUS_VAT
			,MLHP_SELLING_PRICE
			,MLHP_VAT_SELL
			,MLHP_AVERAGE_PRICE_80
			,MLHP_DOWN_AMT_FLAG
			,MLHP_VAT_DOWN_COM_PAY_FLAG
			,MLHP_DOWN_PAYMENT_AMT
			,MLHP_DOWN_PERCENT
			,MLHP_VAT_DOWN_FLAG
			,MLHP_VAT_DOWN
			,MLHP_DOWN_PAYMENT_FLAG
			,MLHP_INVENSTMENT_AMT
			,MLHP_VAT_INVENSTMENT
			,MLHP_HIRING_CHARGE
			,MLHP_VAT_HIRING_CHARGE
			,MLHP_FLAG_RATE
			,MLHP_ROUND_FLAG
			,MLHP_FLAT_RATE
			,MLHP_EFFECTIVE_RATE
			,MLHP_FLAT_RATE_PER_MONTH
			,MLHP_DUE_BALANCE
			,MLHP_VAT_DUE_BALANCE
			,MLHP_OUTSTANDING_BALANCE
			,MLHP_DEALER_CODE
			,MLHP_FROM_SHOWROOM
			,MLHP_SELLMAN_CODE
			,MLHP_PAY_PERIOD_AMOUNT
			,MLHP_VAT_PAY_PERIOD
			,MLHP_PAY_LAST_PERIOD_AMOUNT
			,MLHP_VAT_PAY_LAST_PERIOD
			,MLHP_COLLATERAL_NO
			,MLHP_DR_AC
			,MLHP_REMARK_3
			,MLHP_SPECIAL_CONDITION
			,MLHP_CUSTOMER_POSITION
			,MLHP_BEGIN_ENDIND_FLAG
			,MLHP_SUBSIDIZED_RATE
			,MLHP_SUBSIDIZED_AMOUNT
			,MLHP_DEDUCTION_FLAG
			,MLHP_DEDUCTION_BASE_AMT
			,MLHP_DEDUCTION_VAT
			,MLHP_DEDUCTION_WH_TAX
			,MLHP_DEDUCTION_PIAD_AMT
			,MLHP_COMPANY_WHD_TAX_RATE
			,MLHP_COMPANY_INC_TAX_RATE
			,MLHP_COMPANY_DEDUCTION_RATE
			,MLHP_PRINT_RECEIPT_STATUS
			,MLHP_RECEIPT_NO
			,MLHP_PRINT_TAX_INVOICE_STATUS
			,MLHP_TAX_INVOICE_NO
			,MLHP_PRINT_RECEIPT_DEDUCT_STS
			,MLHP_RECEIPT_DEDUCT_NO
			,MLHP_PRINT_VAT_DEDUCT_STATUS
			,MLHP_VAT_DEDUCT_NO
			,MLHP_PRINT_RECEIPT_SUBSIDY_ST
			,MLHP_RECEIPT_SUBSIDY_NO
			,MLHP_PRINT_VAT_SUBSIDY_STATUS
			,MLHP_VAT_SUBSIDY_NO
			,MLHP_VAT_RATE
			,MLHP_DARFT_FLAG
			,MLHP_DEDUCT_INS_AMT
			,MLHP_RECEIVER_CODE
			,MLHP_DOWN_INCLUDE_VAT
			,MLHP_CREDITOR_CODE
			,MLHP_CHECKER_CODE
			,MLHP_PURPOSE_HPLS
			,MLHP_TR_FROM_DOC_NO
			,MLHP_LIFE_INS_FLAG
			,MLHP_LIFE_INS_AMT
			,MLHP_LIFE_INS_AMT_INC_TO_INVEST
			,MLHP_MARKETING_DATE
			,MLHP_INSURANCE_FLAG
			,MLHP_INSURANCE_AMT
			,MLHP_LATE_CHARGE_CODE
			,MLHP_LATE_CHARGE_SPREAD
			,MLHP_ADJ_INSURANCE_AMT
			,MLHP_ADJ_INSURANCE_VAT
			,MLHP_ADJ_INSURANCE_INC_VAT
			,MLHP_INSTALLMENT_FLAG
			,MLHP_TERM_CALCULATE_COMM
			,MLHP_FLAG
			,MLHP_SUBSIDIZED_WH_AMOUNT
			,MLHP_FIN_AMT_SUBSIDIZED
			,MLHP_SUBSIDIZED_NET_VAT
			,MLHP_NET_EFFECTIVE_RATE
			,MLHP_NET_SUBSIDY_RATE
			,MLHP_NET_EXPENSE_RATE
			,MLHP_NET_UNEARN_RATE
			,MLHP_NET_INS_FREE_RATE
			,MLHP_LIFE_INS_DATE
			,MLHP_LIFE_INS_PERIOD
			,MLHP_LIFE_INS_AMT_PER_MONTH
			,MLHP_HEALTH_INS_AMT
			,MLHP_ADJ_HEALTH_INS_AMT
			,MLHP_ADJ_HEALTH_INS_VAT
			,MLHP_ADJ_HEALTH_INS_INC_VAT
			,MLHP_BEGIN_PAY_PERIOD_AMT
			,MLHP_NET_LIFE_INS_RATE
			,MLHP_NET_HEALTH_INS_RATE
			,MLHP_ASSET_TAX_INVOICE_NO
			,MLHP_INPUT_FLAT_RATE
			,MLHP_INPUT_EFFECTIVE_RATE
			,MLHP_INPUT_FLAT_RATE_PER_MONTH
			,MLHP_LIFE_INS_AMT_EXD_VAT
			,MLHP_ATM_NO
			,MLHP_CONSULT_FLAG
			,MLHP_CONTROL_OWNER
			,MLHP_PERIOD_INSTALL_PRINCIPAL
			,MLHP_STANDARD_CAR_PRICE
			,MLHP_ADVANCE_INSTALLMENT_TERM
			,MLHP_ADVANCE_INSTALLMENT_AMT
			,MLHP_LIFE_INS_AMT_ORG
			,MLHP_LIFE_INS_AMT_PER_MONTH_ORG
			,MLHP_LIFE_INS_AMT_EXD_VAT_ORG
			,MLHP_BEG_INVENSTMENT_AMT
			,MLHP_BEG_VAT_INVENSTMENT
			,MLHP_ADVANCE_BY_CUSTOMER_TERM
			,MLHP_ADVANCE_BY_CUSTOMER_AMT
			,MLHP_ADVANCE_INSTALLMENT_ADJ
			,MLHP_LIMIT_FEE_AMOUNT
			,MLHP_LIMIT_FEE_VAT_AMOUNT
			,MLHP_PA_FLAG
			,MLHP_PA_CODE
			,MLHP_PA_AMOUNT
			,MLHP_BANK_CODE
			,MLHP_ACCOUNT_NO
			,MLHP_SCAN_DATE 
			,MLHP_UPLOAD_DATE 
			,MLHP_SENT_RCV_BY 
			,MLHP_CUSTYPE_FROM 
			,MLHP_REFINAN_NUM 
			,MLHP_CHANG_ADD 
			,NULL AS JOB_RUN_KEY
			,'TELS' AS SOURCE_SYSTEM_CODE
			,'FNMLHP' AS SOURCE_TABLE_NAME
			,'N' DELETED_FLAG
			,LMH.MLMH_MTN_DATE_TIME AS SOURCE_LAST_UPDATE_DATE_TIME --Remark. Need to get MLMH_MTN_DATE_TIME from FNMLMH to get last update time.
			,NULL AS LAST_UPDATE_DATE_TIME
	
FROM FNMLHP LHP WITH(NOLOCK)
INNER JOIN  FNMLMH LMH WITH(NOLOCK) ON LHP.[MLHP_REQ_DOC] = LMH.[MLMH_REQ_DOC]
GO
PRINT SUBSTRING(CONVERT(NVARCHAR(33),CURRENT_TIMESTAMP,121),1,19) + ': V_TADS_STG_TNB_TRN_CONTRACT VIEW CREATED.'
--------------------------------------------------------------------------------------------------------------------------

--STG_TNB_TRN_APPLICATION
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_TRN_APPLICATION')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_TRN_APPLICATION 
	END
GO
CREATE VIEW BI.V_TADS_STG_TNB_TRN_APPLICATION
AS SELECT MLMH_REC_STS
		,MLMH_LN_TYP
		,MLMH_BRN_DOC
		,MLMH_REQ_DOC
		,MLMH_DOC_NO
		,MLMH_CHECK_DIGIT
		,MLMH_CORE_BANK_ACCTNO
		,MLMH_DOC_DATE
		,MLMH_AST_FLAG
		,MLMH_REJECT_FLAG
		,MLMH_CFR_LINE_NO
		,MLMH_PURPOSE_CODE
		,MLMH_PRD_COD
		,MLMH_AO_COD
		,MLMH_ORIGINAL_AMOUNT
		,MLMH_OUTSTANDING_BALANCE
		,MLMH_YESTERDAY_OS_BAL
		,MLMH_AR_CUR_MTH
		,MLMH_PAID_PRN_CUR
		,MLMH_PAID_VAT_CUR
		,MLMH_CONTACT_DATE
		,MLMH_LOAN_DATE
		,MLMH_MATURITY_DATE
		,MLMH_COLLECTION_TYPE
		,MLMH_COLLECTOR_CODE
		,MLMH_COLLECTION_AREA
		,MLMH_PAY_PRINCIPAL_DAY
		,MLMH_PAY_INTEREST_DAY
		,MLMH_PERIOD_INSTALL_PRINCIPAL
		,MLMH_PERIOD_INSTALL_INTEREST
		,MLMH_START_PAY_PRINCIPAL_DATE
		,MLMH_START_PAY_INTEREST_DATE
		,MLMH_SUP_ID_APPROVE_REQUEST
		,MLMH_APPROVE_REQUEST_DATE
		,MLMH_REQUEST_STATUS
		,MLMH_SUP_ID_APPROVE_LOAN
		,MLMH_APPROVE_LOAN_DATE
		,MLMH_STATUS_FLAG
		,MLMH_CHANGE_STATUS_DATE
		,MLMH_TR_BRN_DOC
		,MLMH_TR_REQ_DOC
		,MLMH_TR_DOC_NO
		,MLMH_TR_CHECK_DIGIT
		,MLMH_TR_TO_BRN_DOC
		,MLMH_TR_TO_REQ_DOC
		,MLMH_LAST_CAL_INTEREST_DATE
		,MLMH_LAST_PAY_DOC_TYPE
		,MLMH_LAST_PAY_BRANCH
		,MLMH_LAST_PAY_YEAR
		,MLMH_LAST_PAY_NO
		,MLMH_LAST_PAY_DATE
		,MLMH_NEXT_PAY_PRINCIPAL_DATE
		,MLMH_NEXT_PAY_INTEREST_DATE
		,MLMH_LST_PAY_PERIOD_PRINCIPAL
		,MLMH_LST_PAY_PERIOD_VAT
		,MLMH_BAL_INSTALL_NEXT_PRINC
		,MLMH_BAL_INSTALL_NEXT_INT
		,MLMH_BAL_INSTALL_NEXT_VAT
		,MLMH_CHEQUE_EFFECT_FLAG
		,MLMH_CANCEL_DATE
		,MLMH_REJECT_REASON_CODE
		,MLMH_REQ_DATE_TIME
		,MLMH_CHQ_DATE_TIME
		,MLMH_AST_STS
		,MLMH_APPROXIMATE_CLOSE_AC
		,MLMH_CREATE_MM
		,MLMH_CREATE_YY
		,MLMH_SEND_REQ_DATE
		,MLMH_SEND_REQ_MM
		,MLMH_SEND_REQ_YY
		,MLMH_APPROVE_RQ_MM
		,MLMH_APPROVE_RQ_YY
		,MLMH_APPROVE_LN_MM
		,MLMH_APPROVE_LN_YY
		,MLMH_CANCEL_MM
		,MLMH_CANCEL_YY
		,MLMH_PO_DATE
		,MLMH_INV_LB_FLAG
		,MLMH_INV_LB_DATE
		,MLMH_INV_LB_BY_USER
		,MLMH_SETTLEMENT_PENDING_FLAG
		,MLMH_STANDARD_CAR_PRICE
		,MLMH_SETTLEMENT_PENDING_DATE
		,MLMH_INCREASE_CAR_PRICE
		,MLMH_ASSIGN_APPL_TO_CREDIT
		,MLMH_RETURN_CASE_TO
		,MLMH_DECREASE_CAR_PRICE
		,MLMH_DATE_ON_CHEQUE
		,MLMH_SEND_INVOICE_TO
		,MLMH_FREE_DEC_4
		,MLMH_FLAG_INS_TR
		,MLMH_FLAG_ACT_TR
		,MLMH_FLAG_INS_DEL
		,MLMH_FLAG_ACT_DEL
		,MLMH_MTN_TERMINAL_ID
		,MLMH_MTN_PROGRAM_ID
		,MLMH_MTN_BRANCH_CODE
		,MLMH_MTN_USER_ID
		,MLMH_MTN_DATE_TIME
		,MLMH_COR_DOC_BRN
		,MLMH_COR_DOC_YY
		,MLMH_COR_DOC_NO
		,MLMH_CRA_BRN_DOC
		,MLMH_CRA_REQ_DOC
		,MLMH_REVOLVING_FLAG
		,MLMH_DISBURSE_DATE
		,MLMH_STOP_VAT_FLAG
		,MLMH_REL_UID_SEQ
		,MLMH_PROJECT_CODE
		,MLMH_PRODUCT_TYPE
		,MLMH_LN_CHANNEL
		,MLMH_BRANCH_GROUP
		,MLMH_BRANCH_CODE
		,MLMH_SUB_BRANCH_CODE
		,MLMH_BRANCH_CORE_BANK
		,MLMH_GEN_SCRIPT_COMPLETE
		,MLMH_REQ_DOC_OLD
		,MLMH_DOC_RECEIVE_DATE
		,MLMH_MARKETING_SUP
		,MLMH_AREA_MANAGER
		,MLMH_REFERRAL_NO
		,MLMH_GEN_SCRIPT_FACILITY
		,MLMH_BUSINESS_SIZE
		,MLMH_EXCEPTION_AUTO_REJECT
		,MLMH_FLAG
		,MLMH_ACCRUE_INT_LAST_CALC_DATE
		,MLMH_ACCRUE_INT_RATE
		,MLMH_ACCRUE_INT_RATE_CHANGE
		,MLMH_ACCRUE_INT_AMT_PER_DAY
		,MLMH_ACCRUE_INT_ADJ_AMT_TODAY
		,MLMH_ACCRUE_INT_MONTH
		,MLMH_ACCRUE_INT_AMOUNT_OS
		,MLMH_STOP_VAT_DATE
		,MLMH_TAX_INT
		,MLMH_NON_TAX_INT
		,MLMH_SUB_CAMPAIGN_CODE
		,MLMH_CLOSE_ACC_BEFORE_MONTH
		,MLMH_CLOSE_ACC_BEFORE_CHARGE
		,MLMH_STAMP_DUTY
		,MLMH_GUARANTOR_DUTY
		,MLMH_DUPLICATE_DUTY
		,MLMH_CREDIT_RATING
		,MLMH_CLOSE_AMORTIZE_FLAG
		,MLMH_CLOSE_AMORTIZE_DATE
		,MLMH_GRADE
		,MLMH_ACF_NO
		,MLMH_RELIEVE_FLAG
		,MLMH_ACCRUE_INT_AMOUNT_OS_YES
		,MLMH_TAX_INT_YES
		,MLMH_NON_TAX_INT_YES
		,MLMH_PAID_INT_CUR
		,MLMH_ACCRUE_PENALTY_INT
		,MLMH_STOP_ACCRUE_INT
		,MLMH_DOC_YY_REPO
		,MLMH_DOC_NO_REPO
		,MLMH_CUST_ID_BUYER
		,MLMH_PAYBACK_PREV_MONTH
		,MLMH_PAID_PRN_PRV_MTH
		,MLMH_PAID_VAT_PRV_MTH
		,MLMH_DISCOUNT_BEFORE_CLOSING
		,MLMH_REPO_SELL_DATE
		,MLMH_PRINT_CANCEL_LETTER_DATE
		,MLMH_REPO_DATE
		,MLMH_REPO_FLAG
		,MLMH_MSOL_YEAR
		,MLMH_MSOL_MONTH
		,MLMH_BAR_CODE
		,MLMH_COL_GROUP_FLAG
		,MLMH_FIELD_CODE
		,MLMH_CUSTOMER_COME_FROM
		,MLMH_CONSULT_FLAG
		,MLMH_APPROVE_REASON
		,MLMH_LAST_PAYMENT_DATE
		,MLMH_OS_INC_VAT
		,MLMH_COLLECTOR_CODE_OLD
		,MLMH_SEND_NCB
		,MLMH_CHANGE_COLLECTOR_DATE
		,MLMH_WO_DATE
		,MLMH_FORECLOSED_PROPERTIES
		,MLMH_REFIN_LOAN_NO
		,MLMH_REFIN_LOAN_CHK_DIGIT
		,MLMH_LAST_PAY_BY_CODE
		,MLMH_BANK_CODE
		,MLMH_ACCOUNT_NO
		,MLMH_OVERDUE_TERM
		,MLMH_LAST_INTEREST_AMT_OVER
		,MLMH_DOC_NO_SORT
		,MLMH_ADVICE_NAME
		,MLMH_ADVICE_PHONE
		,MLMH_BARCODE_TYPE
		,MLMH_SMILE_CARD_FLAG
		,MLMH_SMILE_CARD_DATE
		,MLMH_SMILE_CARD_AMT
		,MLMH_SCAN_DATE
		,MLMH_UPLOAD_DATE
		,MLMH_CLAIM_INSURANCE
		,MLMH_CLAIM_PAY_DATE
		,NULL AS JOB_RUN_KEY
		,'TELS' AS SOURCE_SYSTEM_CODE
		,'FNMLMH' AS SOURCE_TABLE_NAME
		,'N' DELETED_FLAG
		,LMH.MLMH_MTN_DATE_TIME AS SOURCE_LAST_UPDATE_DATE_TIME
		,NULL AS LAST_UPDATE_DATE_TIME

	
FROM FNMLMH LMH WITH(NOLOCK)
GO
PRINT SUBSTRING(CONVERT(NVARCHAR(33),CURRENT_TIMESTAMP,121),1,19) + ': V_TADS_STG_TNB_TRN_APPLICATION VIEW CREATED.'
--------------------------------------------------------------------------------------------------------------------------

--STG_TNB_TRN_APP_IN_LOG
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_TRN_APP_IN_LOG')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_TRN_APP_IN_LOG
	END
GO
CREATE VIEW BI.V_TADS_STG_TNB_TRN_APP_IN_LOG
AS SELECT [MLRQ_BRN_DOC]
      ,[MLRQ_REQ_DOC]
      ,[MLRQ_START_DATE_TIME]
      ,[MLRQ_STATUS_BEFORE_CHANGE]
      ,[MLRQ_END_DATE_TIME]
      ,[MLRQ_BY_PROGRAM_ID]
      ,[MLRQ_STATUS]
      ,[MLRQ_USER_ID]
      ,[MLRQ_CR_CODE]
	  ,NULL AS JOB_RUN_KEY
	  ,'TELS' AS SOURCE_SYSTEM_CODE
	  ,'FNMLRQ' AS SOURCE_TABLE_NAME
	  ,'N' DELETED_FLAG
	  ,[MLRQ_END_DATE_TIME] AS SOURCE_LAST_UPDATE_DATE_TIME
	  ,NULL AS LAST_UPDATE_DATE_TIME
  FROM FNMLRQ LQR WITH(NOLOCK)
GO
PRINT SUBSTRING(CONVERT(NVARCHAR(33),CURRENT_TIMESTAMP,121),1,19) + ': V_TADS_STG_TNB_TRN_APP_IN_LOG VIEW CREATED.'
--------------------------------------------------------------------------------------------------------------------------

/** Create Master View **/

--STG_TNB_MST_ACCOUNT_STATUS
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_MST_ACCOUNT_STATUS')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_MST_ACCOUNT_STATUS
	END
GO
CREATE VIEW BI.V_TADS_STG_TNB_MST_ACCOUNT_STATUS
AS SELECT [MDSC_STATUS]
		  ,[MDSC_TYP]
		  ,[MDSC_COD]
		  ,[MDSC_LNG]
		  ,[MDSC_DSC]
		  ,[MDSC_GROUP]
		  ,[MDSC_FREE_ALPHA_1]
		  ,[MDSC_FREE_DECIMAL_1]
		  ,[MDSC_MTN_TERMINAL_ID]
		  ,[MDSC_MTN_PROGRAM_ID]
		  ,[MDSC_MTN_BRANCH]
		  ,[MDSC_MTN_USER_ID]
		  ,[MDSC_MTN_DATE]
		  ,NULL AS JOB_RUN_KEY
		  ,'TELS' AS SOURCE_SYSTEM_CODE
		  ,'FNMDSC' AS SOURCE_TABLE_NAME
		  ,'N' DELETED_FLAG
		  ,DSC.MDSC_MTN_DATE AS SOURCE_LAST_UPDATE_DATE_TIME
		  ,NULL AS LAST_UPDATE_DATE_TIME

FROM FNMDSC DSC WITH(NOLOCK)
WHERE MDSC_TYP = 'ACCOUNT-STATUS'

GO
PRINT SUBSTRING(CONVERT(NVARCHAR(33),CURRENT_TIMESTAMP,121),1,19) + ': V_TADS_STG_TNB_MST_ACCOUNT_STATUS VIEW CREATED.'
--------------------------------------------------------------------------------------------------------------------------

--STG_TNB_MST_REQUEST_STATUS
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_MST_REQUEST_STATUS')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_MST_REQUEST_STATUS
	END
GO
CREATE VIEW BI.V_TADS_STG_TNB_MST_REQUEST_STATUS
AS SELECT [MDSC_STATUS]
		  ,[MDSC_TYP]
		  ,[MDSC_COD]
		  ,[MDSC_LNG]
		  ,[MDSC_DSC]
		  ,[MDSC_GROUP]
		  ,[MDSC_FREE_ALPHA_1]
		  ,[MDSC_FREE_DECIMAL_1]
		  ,[MDSC_MTN_TERMINAL_ID]
		  ,[MDSC_MTN_PROGRAM_ID]
		  ,[MDSC_MTN_BRANCH]
		  ,[MDSC_MTN_USER_ID]
		  ,[MDSC_MTN_DATE]
		  ,NULL AS JOB_RUN_KEY
		  ,'TELS' AS SOURCE_SYSTEM_CODE
		  ,'FNMDSC' AS SOURCE_TABLE_NAME
		  ,'N' DELETED_FLAG
		  ,DSC.MDSC_MTN_DATE AS SOURCE_LAST_UPDATE_DATE_TIME
		  ,NULL AS LAST_UPDATE_DATE_TIME

FROM FNMDSC DSC WITH(NOLOCK)
WHERE MDSC_TYP = 'REQUEST-STATUS'

GO
PRINT SUBSTRING(CONVERT(NVARCHAR(33),CURRENT_TIMESTAMP,121),1,19) + ': V_TADS_STG_TNB_MST_REQUEST_STATUS VIEW CREATED.'
--------------------------------------------------------------------------------------------------------------------------
--STG_TNB_MST_PRODUCT
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_MST_PRODUCT')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_MST_PRODUCT
	END
GO
CREATE VIEW BI.V_TADS_STG_TNB_MST_PRODUCT
AS SELECT [MDSC_STATUS]
		  ,[MDSC_TYP]
		  ,[MDSC_COD]
		  ,[MDSC_LNG]
		  ,[MDSC_DSC]
		  ,[MDSC_GROUP]
		  ,[MDSC_FREE_ALPHA_1]
		  ,[MDSC_FREE_DECIMAL_1]
		  ,[MDSC_MTN_TERMINAL_ID]
		  ,[MDSC_MTN_PROGRAM_ID]
		  ,[MDSC_MTN_BRANCH]
		  ,[MDSC_MTN_USER_ID]
		  ,[MDSC_MTN_DATE]
		  ,NULL AS JOB_RUN_KEY
		  ,'TELS' AS SOURCE_SYSTEM_CODE
		  ,'FNMDSC' AS SOURCE_TABLE_NAME
		  ,'N' DELETED_FLAG
		  ,DSC.MDSC_MTN_DATE AS SOURCE_LAST_UPDATE_DATE_TIME
		  ,NULL AS LAST_UPDATE_DATE_TIME
FROM FNMDSC DSC WITH(NOLOCK)
WHERE MDSC_TYP = 'ProjectCode'

GO
PRINT SUBSTRING(CONVERT(NVARCHAR(33),CURRENT_TIMESTAMP,121),1,19) + ': V_TADS_STG_TNB_MST_CUST_SOURCE VIEW CREATED.'
--------------------------------------------------------------------------------------------------------------------------
--STG_TNB_MST_CUST_SOURCE
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_MST_CUST_SOURCE')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_MST_CUST_SOURCE 
	END
GO
CREATE VIEW BI.V_TADS_STG_TNB_MST_CUST_SOURCE
AS SELECT [MDSC_STATUS]
		  ,[MDSC_TYP]
		  ,[MDSC_COD]
		  ,[MDSC_LNG]
		  ,[MDSC_DSC]
		  ,[MDSC_GROUP]
		  ,[MDSC_FREE_ALPHA_1]
		  ,[MDSC_FREE_DECIMAL_1]
		  ,[MDSC_MTN_TERMINAL_ID]
		  ,[MDSC_MTN_PROGRAM_ID]
		  ,[MDSC_MTN_BRANCH]
		  ,[MDSC_MTN_USER_ID]
		  ,[MDSC_MTN_DATE]
		  ,NULL AS JOB_RUN_KEY
		  ,'TELS' AS SOURCE_SYSTEM_CODE
		  ,'FNMDSC' AS SOURCE_TABLE_NAME
		  ,'N' DELETED_FLAG
		  ,DSC.MDSC_MTN_DATE AS SOURCE_LAST_UPDATE_DATE_TIME
		  ,NULL AS LAST_UPDATE_DATE_TIME

FROM FNMDSC DSC WITH(NOLOCK)
WHERE MDSC_TYP = 'CUSTOMER-COME-FROM'

GO
PRINT SUBSTRING(CONVERT(NVARCHAR(33),CURRENT_TIMESTAMP,121),1,19) + ': V_TADS_STG_TNB_MST_CUST_SOURCE VIEW CREATED.'
--------------------------------------------------------------------------------------------------------------------------
--STG_TNB_MST_CUST_SOURCE
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_MST_CUST_TYPE')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_MST_CUST_TYPE 
	END
GO
CREATE VIEW BI.V_TADS_STG_TNB_MST_CUST_TYPE
AS SELECT [MDSC_STATUS]
		  ,[MDSC_TYP]
		  ,[MDSC_COD]
		  ,[MDSC_LNG]
		  ,[MDSC_DSC]
		  ,[MDSC_GROUP]
		  ,[MDSC_FREE_ALPHA_1]
		  ,[MDSC_FREE_DECIMAL_1]
		  ,[MDSC_MTN_TERMINAL_ID]
		  ,[MDSC_MTN_PROGRAM_ID]
		  ,[MDSC_MTN_BRANCH]
		  ,[MDSC_MTN_USER_ID]
		  ,[MDSC_MTN_DATE]
		  ,NULL AS JOB_RUN_KEY
		  ,'TELS' AS SOURCE_SYSTEM_CODE
		  ,'FNMDSC' AS SOURCE_TABLE_NAME
		  ,'N' DELETED_FLAG
		  ,DSC.MDSC_MTN_DATE AS SOURCE_LAST_UPDATE_DATE_TIME
		  ,NULL AS LAST_UPDATE_DATE_TIME
FROM FNMDSC DSC WITH(NOLOCK)
WHERE MDSC_TYP = 'Custypefrom'	
GO
PRINT SUBSTRING(CONVERT(NVARCHAR(33),CURRENT_TIMESTAMP,121),1,19) + ': V_TADS_STG_TNB_MST_CUST_TYPE VIEW CREATED.'
--------------------------------------------------------------------------------------------------------------------------

--STG_TNB_MST_BRANCH
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_MST_BRANCH')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_MST_BRANCH 
	END
GO
CREATE VIEW BI.V_TADS_STG_TNB_MST_BRANCH
AS SELECT [MDLR_STATUS]
		  ,[MDLR_DEALER_CODE]
		  ,[MDLR_TITLE_CODE]
		  ,[MDLR_DEALER_NAME_THAI]
		  ,[MDLR_DEALER_NAME_ENGLISH]
		  ,[MDLR_ADDR_NO]
		  ,[MDLR_ADDR_MOO]
		  ,[MDLR_ADDR_BUILDING]
		  ,[MDLR_ADDR_SOI]
		  ,[MDLR_ADDR_ROAD]
		  ,[MDLR_ADDR_TUMPON]
		  ,[MDLR_ADDR_AMPUR]
		  ,[MDLR_ADDR_CHANGWAT]
		  ,[MDLR_ADDR_ZIP_CODE]
		  ,[MDLR_TELEPHONE]
		  ,[MDLR_FAX_NO]
		  ,[MDLR_EMAIL_ADDR]
		  ,[MDLR_CONTACT_PERSON]
		  ,[MDLR_COMM_PERCENT]
		  ,[MDLR_CHEQUE_NAME]
		  ,[MDLR_VAT_ADR1]
		  ,[MDLR_VAT_ADR2]
		  ,[MDLR_VAT_ADR3]
		  ,[MDLR_VAT_ADR4]
		  ,[MDLR_TAX_ID]
		  ,[MDLR_CHEQUE_TYPE]
		  ,[MDLR_PAY_COMM_FLAG]
		  ,[MDLR_HIR_CORP_RATE]
		  ,[MDLR_COMM_WH]
		  ,[MDLR_HIR_IND_RATE]
		  ,[MDLR_COMM_WH_IND]
		  ,[MDLR_CHANG_HIR_RATE_FLAG]
		  ,[MDLR_CHEQUE_TYPE_COM_FIN]
		  ,[MDLR_CHEQUE_TYPE_COM_FIN_1]
		  ,[MDLR_PAY_INS_FLAG]
		  ,[MDLR_COMM_INS_AMT]
		  ,[MDLR_INS_WH]
		  ,[MDLR_CHANG_INS_AMT_FLAG]
		  ,[MDLR_CHEQUE_TYPE_COM_INS]
		  ,[MDLR_CHEQUE_TYPE_COM_INS_1]
		  ,[MDLR_DEALER_GROUP]
		  ,[MDLR_CHEQUE_FLAG]
		  ,[MDLR_OTHER_FLAG]
		  ,[MDLR_IN_VAT_SYSTEM]
		  ,[MDLR_ABSORB_VAT]
		  ,[MDLR_DARFT_FLAG]
		  ,[MDLR_TRANSFER_TO_BNK]
		  ,[MDLR_TRANSFER_TO_BRN]
		  ,[MDLR_TRANSFER_TO_AC_TYPE]
		  ,[MDLR_ACCOUNT_NO]
		  ,[MDLR_CREDIT_CODE]
		  ,[MDLR_PO_FLAG]
		  ,[MDLR_PO_DEALER_HO]
		  ,[MDLR_AO_COD]
		  ,[MDLR_PO_NAME]
		  ,[MDLR_PO_INSURANCE_FLAG]
		  ,[MDLR_PO_COMM_RATE_FLAG]
		  ,[MDLR_ASSET_BRAND]
		  ,[MDLR_FREE_DEC_1]
		  ,[MDLR_FREE_ALPHA_2]
		  ,[MDLR_SALESMAN_RUN_NO]
		  ,[MDLR_BASE_CALULATE_COMM]
		  ,[MDLR_BASE_CALCULATE_CHANGE]
		  ,[MDLR_ASSET_TYPE]
		  ,[MDLR_CORE_BANK_CODE]
		  ,[MDLR_LIFE_INS_AMT_INC_TO_INVEST]
		  ,[MDLR_PAY_ASSET_TYPE]
		  ,[MDLR_PAY_ASSET_BNK_CODE]
		  ,[MDLR_PAY_ASSET_ACC_NO]
		  ,[MDLR_PAY_COMM_ASSET_TYPE]
		  ,[MDLR_PAY_COMM_ASSET_BNK_CODE]
		  ,[MDLR_PAY_COMM_ASSET_ACC_NO]
		  ,[MDLR_PAY_COMM_INS_TYPE]
		  ,[MDLR_PAY_COMM_INS_BNK_CODE]
		  ,[MDLR_PAY_COMM_INS_ACC_NO]
		  ,[MDLR_PAY_EXTRA_COMM_TYPE]
		  ,[MDLR_PAY_EXTRA_COMM_BNK_CODE]
		  ,[MDLR_PAY_EXTRA_COMM_ACC_NO]
		  ,[MDLR_ADDITIONAL_CONDITION]
		  ,[MDLR_MTN_TERMINAL_ID]
		  ,[MDLR_MTN_PROGRAM_ID]
		  ,[MDLR_MTN_BRANCH_CODE]
		  ,[MDLR_MTN_USER_ID]
		  ,[MDLR_MTN_DATE_TIME]
		  ,[MDLR_APPROVED_BY]
		  ,[MDLR_APPROVED_DATE]
		  ,[MDLR_RUNNING]
		  ,[MDLR_STATUS_PROCESS]
		  ,[MDLR_BRACH_ACC_CODE]
		  ,[MDLR_CONTRACT_DATE]
		  ,[MDLR_LAST_BOOK_LOAN_DATE]
		  ,[MDLR_TAKE_CARE_BY_BRANCH_CODE]
		  ,[MDLR_BRANCH_ID]
		  ,NULL AS JOB_RUN_KEY
		  ,'TELS' AS SOURCE_SYSTEM_CODE
		  ,'HPMDLR' AS SOURCE_TABLE_NAME
		  ,'N' DELETED_FLAG
		  ,DLR.MDLR_MTN_DATE_TIME AS SOURCE_LAST_UPDATE_DATE_TIME
		  ,NULL AS LAST_UPDATE_DATE_TIME

FROM HPMDLR DLR WITH(NOLOCK)
WHERE MDLR_DEALER_CODE LIKE 'T%' AND MDLR_TITLE_CODE = '08001'
GO
PRINT SUBSTRING(CONVERT(NVARCHAR(33),CURRENT_TIMESTAMP,121),1,19) + ': V_TADS_STG_TNB_MST_BRANCH VIEW CREATED.'
--------------------------------------------------------------------------------------------------------------------------
--STG_TNB_MST_DEALER
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_MST_DEALER')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_MST_DEALER 
	END
GO
CREATE VIEW BI.V_TADS_STG_TNB_MST_DEALER
AS SELECT [MDLR_STATUS]
		  ,[MDLR_DEALER_CODE]
		  ,[MDLR_TITLE_CODE]
		  ,[MDLR_DEALER_NAME_THAI]
		  ,[MDLR_DEALER_NAME_ENGLISH]
		  ,[MDLR_ADDR_NO]
		  ,[MDLR_ADDR_MOO]
		  ,[MDLR_ADDR_BUILDING]
		  ,[MDLR_ADDR_SOI]
		  ,[MDLR_ADDR_ROAD]
		  ,[MDLR_ADDR_TUMPON]
		  ,[MDLR_ADDR_AMPUR]
		  ,[MDLR_ADDR_CHANGWAT]
		  ,[MDLR_ADDR_ZIP_CODE]
		  ,[MDLR_TELEPHONE]
		  ,[MDLR_FAX_NO]
		  ,[MDLR_EMAIL_ADDR]
		  ,[MDLR_CONTACT_PERSON]
		  ,[MDLR_COMM_PERCENT]
		  ,[MDLR_CHEQUE_NAME]
		  ,[MDLR_VAT_ADR1]
		  ,[MDLR_VAT_ADR2]
		  ,[MDLR_VAT_ADR3]
		  ,[MDLR_VAT_ADR4]
		  ,[MDLR_TAX_ID]
		  ,[MDLR_CHEQUE_TYPE]
		  ,[MDLR_PAY_COMM_FLAG]
		  ,[MDLR_HIR_CORP_RATE]
		  ,[MDLR_COMM_WH]
		  ,[MDLR_HIR_IND_RATE]
		  ,[MDLR_COMM_WH_IND]
		  ,[MDLR_CHANG_HIR_RATE_FLAG]
		  ,[MDLR_CHEQUE_TYPE_COM_FIN]
		  ,[MDLR_CHEQUE_TYPE_COM_FIN_1]
		  ,[MDLR_PAY_INS_FLAG]
		  ,[MDLR_COMM_INS_AMT]
		  ,[MDLR_INS_WH]
		  ,[MDLR_CHANG_INS_AMT_FLAG]
		  ,[MDLR_CHEQUE_TYPE_COM_INS]
		  ,[MDLR_CHEQUE_TYPE_COM_INS_1]
		  ,[MDLR_DEALER_GROUP]
		  ,[MDLR_CHEQUE_FLAG]
		  ,[MDLR_OTHER_FLAG]
		  ,[MDLR_IN_VAT_SYSTEM]
		  ,[MDLR_ABSORB_VAT]
		  ,[MDLR_DARFT_FLAG]
		  ,[MDLR_TRANSFER_TO_BNK]
		  ,[MDLR_TRANSFER_TO_BRN]
		  ,[MDLR_TRANSFER_TO_AC_TYPE]
		  ,[MDLR_ACCOUNT_NO]
		  ,[MDLR_CREDIT_CODE]
		  ,[MDLR_PO_FLAG]
		  ,[MDLR_PO_DEALER_HO]
		  ,[MDLR_AO_COD]
		  ,[MDLR_PO_NAME]
		  ,[MDLR_PO_INSURANCE_FLAG]
		  ,[MDLR_PO_COMM_RATE_FLAG]
		  ,[MDLR_ASSET_BRAND]
		  ,[MDLR_FREE_DEC_1]
		  ,[MDLR_FREE_ALPHA_2]
		  ,[MDLR_SALESMAN_RUN_NO]
		  ,[MDLR_BASE_CALULATE_COMM]
		  ,[MDLR_BASE_CALCULATE_CHANGE]
		  ,[MDLR_ASSET_TYPE]
		  ,[MDLR_CORE_BANK_CODE]
		  ,[MDLR_LIFE_INS_AMT_INC_TO_INVEST]
		  ,[MDLR_PAY_ASSET_TYPE]
		  ,[MDLR_PAY_ASSET_BNK_CODE]
		  ,[MDLR_PAY_ASSET_ACC_NO]
		  ,[MDLR_PAY_COMM_ASSET_TYPE]
		  ,[MDLR_PAY_COMM_ASSET_BNK_CODE]
		  ,[MDLR_PAY_COMM_ASSET_ACC_NO]
		  ,[MDLR_PAY_COMM_INS_TYPE]
		  ,[MDLR_PAY_COMM_INS_BNK_CODE]
		  ,[MDLR_PAY_COMM_INS_ACC_NO]
		  ,[MDLR_PAY_EXTRA_COMM_TYPE]
		  ,[MDLR_PAY_EXTRA_COMM_BNK_CODE]
		  ,[MDLR_PAY_EXTRA_COMM_ACC_NO]
		  ,[MDLR_ADDITIONAL_CONDITION]
		  ,[MDLR_MTN_TERMINAL_ID]
		  ,[MDLR_MTN_PROGRAM_ID]
		  ,[MDLR_MTN_BRANCH_CODE]
		  ,[MDLR_MTN_USER_ID]
		  ,[MDLR_MTN_DATE_TIME]
		  ,[MDLR_APPROVED_BY]
		  ,[MDLR_APPROVED_DATE]
		  ,[MDLR_RUNNING]
		  ,[MDLR_STATUS_PROCESS]
		  ,[MDLR_BRACH_ACC_CODE]
		  ,[MDLR_CONTRACT_DATE]
		  ,[MDLR_LAST_BOOK_LOAN_DATE]
		  ,[MDLR_TAKE_CARE_BY_BRANCH_CODE]
		  ,[MDLR_BRANCH_ID]
		  ,NULL AS JOB_RUN_KEY
		  ,'TELS' AS SOURCE_SYSTEM_CODE
		  ,'HPMDLR' AS SOURCE_TABLE_NAME
		  ,'N' DELETED_FLAG
		  ,DLR.MDLR_MTN_DATE_TIME AS SOURCE_LAST_UPDATE_DATE_TIME
		  ,NULL AS LAST_UPDATE_DATE_TIME

FROM HPMDLR DLR WITH(NOLOCK)
WHERE MDLR_DEALER_CODE LIKE 'SB%' 

GO

PRINT SUBSTRING(CONVERT(NVARCHAR(33),CURRENT_TIMESTAMP,121),1,19) + ': V_TADS_STG_TNB_MST_DEALER VIEW CREATED.'
--------------------------------------------------------------------------------------------------------------------------

--STG_TNB_MST_BOT_CLASS
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_MST_BOT_CLASS')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_MST_BOT_CLASS
	END
GO
CREATE VIEW BI.V_TADS_STG_TNB_MST_BOT_CLASS
AS SELECT [MDSC_STATUS]
		  ,[MDSC_TYP]
		  ,[MDSC_COD]
		  ,[MDSC_LNG]
		  ,[MDSC_DSC]
		  ,[MDSC_GROUP]
		  ,[MDSC_FREE_ALPHA_1]
		  ,[MDSC_FREE_DECIMAL_1]
		  ,[MDSC_MTN_TERMINAL_ID]
		  ,[MDSC_MTN_PROGRAM_ID]
		  ,[MDSC_MTN_BRANCH]
		  ,[MDSC_MTN_USER_ID]
		  ,[MDSC_MTN_DATE]
		  ,NULL AS JOB_RUN_KEY
		  ,'TELS' AS SOURCE_SYSTEM_CODE
		  ,'FNMDSC' AS SOURCE_TABLE_NAME
		  ,'N' DELETED_FLAG
		  ,DSC.MDSC_MTN_DATE AS SOURCE_LAST_UPDATE_DATE_TIME
		  ,NULL AS LAST_UPDATE_DATE_TIME

FROM FNMDSC DSC WITH(NOLOCK)
WHERE MDSC_TYP = 'BOT-GRADE'

GO
PRINT SUBSTRING(CONVERT(NVARCHAR(33),CURRENT_TIMESTAMP,121),1,19) + ': V_TADS_STG_TNB_MST_BOT_CLASS VIEW CREATED.'
