-- The below views need to be created at TNB DB
-- Create BI.V_TADS_STG_TNB_MST_CUSTOMER_INFO
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_MST_CUSTOMER_INFO')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_MST_CUSTOMER_INFO
	END
GO
CREATE VIEW BI.V_TADS_STG_TNB_MST_CUSTOMER_INFO
AS SELECT [MINF_STATUS]
      ,[MINF_CUSTOMER_ID]
      ,[MINF_INVOLVED_PARTY_TYPE]
      ,[MINF_CUSTOMER_TYPE]
      ,[MINF_TITLE_NAME_THAI]
      ,[MINF_FIRST_NAME_THAI]
      ,[MINF_MIDDLE_NAME_THAI]
      ,[MINF_LAST_NAME_THAI]
      ,[MINF_TITLE_NAME_ENGLISH]
      ,[MINF_FIRST_NAME_ENGLISH]
      ,[MINF_MIDDLE_NAME_ENGLISH]
      ,[MINF_LAST_NAME_ENGLISH]
      ,[MINF_FIRST_NAME_THAI_IDX]
      ,[MINF_LAST_NAME_THAI_IDX]
      ,[MINF_FIRST_NAME_ENGLISH_IDX]
      ,[MINF_LAST_NAME_ENGLISH_IDX]
      ,[MINF_EMAIL_ADDR]
      ,[MINF_MOBILE_TEL]
      ,[MINF_MOBILE_TEL2]
      ,[MINF_MOBILE_TEL3]
      ,[MINF_CONTACT_DATE]
      ,[MINF_BOT_NO]
      ,[MINF_NATIONALITY]
      ,[MINF_RESIDENCE]
      ,[MINF_AO_CODE]
      ,[MINF_CREDIT_CODE]
      ,[MINF_GROUP_CODE]
      ,[MINF_REMARK]
      ,[MINF_CRT_USER_ID]
      ,[MINF_CRT_DATE_TIME]
      ,[MINF_MTN_TERMINAL_ID]
      ,[MINF_MTN_PROGRAM_ID]
      ,[MINF_MTN_BRANCH_CODE]
      ,[MINF_MTN_USER_ID]
      ,[MINF_MTN_DATE_TIME]
      ,[MINF_APPROVED_BY]
      ,[MINF_APPROVED_DATE]
      ,[MINF_RUNNING]
      ,[MINF_STATUS_PROCESS]
      ,[MINF_AS400_CUSTOMER_ID]
      ,[MINF_KYC_LEVEL]
      ,[MINF_FLAG]
      ,[MINF_NICK_NAME]
      ,[MINF_ID_CARD]
      ,[MINF_CUST_BRN_ID]
      ,[MINF_LETTER_RETURN_FLAG]
      ,[MINF_LETTER_RETURN_REASON]
      ,[MINF_LETTER_RETURN_DATE]
      ,[MINF_ASSET_AMOUNT]
      ,[MINF_TOTAL_STAFF]
	  ,NULL AS JOB_RUN_KEY
	  ,'TELS' AS SOURCE_SYSTEM_CODE
	  ,'CIMINF' AS SOURCE_TABLE_NAME
	  ,'N' DELETED_FLAG
	  ,[MINF_MTN_DATE_TIME] AS SOURCE_LAST_UPDATE_DATE_TIME
	  ,NULL AS LAST_UPDATE_DATE_TIME
  FROM CIMINF INF WITH(NOLOCK)
GO
PRINT SUBSTRING(CONVERT(NVARCHAR(33),CURRENT_TIMESTAMP,121),1,19) + ': V_TADS_STG_TNB_MST_CUSTOMER_INFO VIEW CREATED.'

-- Create BI.V_TADS_STG_TNB_MST_LOAN_CUST
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_MST_LOAN_CUST')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_MST_LOAN_CUST
	END
GO
CREATE VIEW [BI].[V_TADS_STG_TNB_MST_LOAN_CUST]
AS SELECT MLMC_REC_STS,
		  MLMC_LN_TYP,
		  MLMC_BRN_DOC,
		  MLMC_REQ_DOC,
		  MLMC_DOC_NO,
		  MLMC_CHECK_DIGIT,
		  MLMC_CIS_NO,
		  MLMC_CIS_TYPE,
		  MLMC_INCOME_AMOUNT,
		  MLMC_LIABILITY_AMOUNT,
		  MLMC_RELATION_TYPE,
		  MLMC_INCOME_FLAG,
		  MLMC_CHECKER_CODE,
		  MLMC_NONEED_FLAG,
		  MLMC_SPECIAL_ADDR_FLAG,
		  MLMC_FLAG,
		  MLMC_CONSENT_RECEIVED_FLAG,
		  MLMC_CONSENT_RECEIVED_DATE,
		  MLMC_CONSENT_RECEIVED_USER_ID,
		  NULL AS JOB_RUN_KEY,
		  'TELS' AS SOURCE_SYSTEM_CODE,
		  'FNMLMC' AS SOURCE_TABLE_NAME,
		  'N' DELETED_FLAG,
		  MLMH_MTN_DATE_TIMEAS SOURCE_LAST_UPDATE_DATE_TIME,
		  NULL AS LAST_UPDATE_DATE_TIME
FROM FNMLMC WITH(NOLOCK)
INNER JOIN FNMLMH WITH(NOLOCK)
	ON MLMC_REQ_DOC = MLMH_REQ_DOC
GO
PRINT SUBSTRING(CONVERT(NVARCHAR(33),CURRENT_TIMESTAMP,121),1,19) + ': V_TADS_STG_TNB_MST_LOAN_CUST VIEW CREATED.'

-- Create BI.V_TADS_STG_TNB_TRN_APP_IN_LOG
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_TRN_APP_IN_LOG')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_TRN_APP_IN_LOG
	END
GO
CREATE VIEW BI.V_TADS_STG_TNB_TRN_APP_IN_LOG
AS SELECT [MLRQ_BRN_DOC]
      ,[MLRQ_REQ_DOC]
      ,[MLRQ_START_DATE_TIME]
      ,[MLRQ_STATUS_BEFORE_CHANGE]
      ,[MLRQ_END_DATE_TIME]
      ,[MLRQ_BY_PROGRAM_ID]
      ,[MLRQ_STATUS]
      ,[MLRQ_USER_ID]
      ,[MLRQ_CR_CODE]
	  ,NULL AS JOB_RUN_KEY
	  ,'TELS' AS SOURCE_SYSTEM_CODE
	  ,'FNMLRQ' AS SOURCE_TABLE_NAME
	  ,'N' DELETED_FLAG
	  ,[MLRQ_END_DATE_TIME] AS SOURCE_LAST_UPDATE_DATE_TIME
	  ,NULL AS LAST_UPDATE_DATE_TIME
  FROM FNMLRQ LQR WITH(NOLOCK)
GO
PRINT SUBSTRING(CONVERT(NVARCHAR(33),CURRENT_TIMESTAMP,121),1,19) + ': V_TADS_STG_TNB_TRN_APP_IN_LOG VIEW CREATED.'

-- Create BI.V_TADS_STG_TNB_MST_BRANCH_FILE
IF EXISTS (SELECT name FROM sys.views WHERE name = N'V_TADS_STG_TNB_MST_BRANCH_FILE')
	BEGIN
		DROP VIEW BI.V_TADS_STG_TNB_MST_BRANCH_FILE
	END
GO
CREATE VIEW [BI].[V_TADS_STG_TNB_MST_BRANCH_FILE]
AS SELECT 
		MBRN_STATUS,
		MBRN_COM_CODE,
		MBRN_CODE,
		MBRN_FULL_NAME_THAI,
		MBRN_SHORT_NAME_THAI,
		MBRN_FULL_NAME_ENGLISH,
		MBRN_SHORT_NAME_ENGLISH,
		MBRN_ADDR_NO,
		MBRN_ADDR_MOO,
		MBRN_ADDR_BUILDING,
		MBRN_ADDR_SOI,
		MBRN_ADDR_ROAD,
		MBRN_ADDR_TUMPON,
		MBRN_ADDR_AMPUR,
		MBRN_ADDR_CHANGWAT,
		MBRN_ADDR_ZIP_CODE,
		MBRN_TELEPHONE,
		MBRN_FAX_NO,
		MBRN_EMAIL_ADDR,
		MBRN_TAX_ID,
		MBRN_MTN_TERMINAL_ID,
		MBRN_MTN_PROGRAM_ID,
		MBRN_MTN_BRANCH_CODE,
		MBRN_MTN_USER_ID,
		MBRN_MTN_DATE_TIME,
		MBRN_REMITTANCE_GROUP,
		MBRN_INTER_ACC_NO,
		MBRN_INTER_SUBSIDARY,
		MBRN_INTER_SUB_LEDGER,
		MBRN_INTER_ACC_NO_CANCEL,
		MBRN_INTER_SUBSIDARY_CANCEL,
		MBRN_INTER_SUB_LEDGER_CANCEL,
		MBRN_AREA_CODE,
		MBRN_COLLECTOR_HEAD_OF_BRANCH,
		MBRN_COLLECTOR_TEL_EXT,
		NULL AS JOB_RUN_KEY,
		'TELS' AS SOURCE_SYSTEM_CODE,
		'FNMBRN' AS SOURCE_TABLE_NAME,
		'N' DELETED_FLAG,
		MBRN_MTN_DATE_TIME AS SOURCE_LAST_UPDATE_DATE_TIME,
		NULL AS LAST_UPDATE_DATE_TIME
FROM FNMBRN WITH(NOLOCK)
GO
PRINT SUBSTRING(CONVERT(NVARCHAR(33),CURRENT_TIMESTAMP,121),1,19) + ': V_TADS_STG_TNB_MST_BRANCH_FILE VIEW CREATED.'